version: "3.9"
services:
  app1: &app1
    image: rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"
    environment:
      - DATABASE_URL=postgresql://admin:123@postgres:5432/rinha?schema=public&connection_limit=30&pool_timeout=40
      - PORT=9999
  app2:
    <<: *app1
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./pg_hba.conf:/usr/share/postgresql/16/pg_hba.conf
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
     resources:
       limits:
         cpus: "0.4"
         memory: "230MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1